spring.application.name=TOLL-SERVICE
server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-plain-silence-a92hge12-pooler.gwc.azure.neon.tech/neondb?}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_dyqRoO4r9QxM}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=https://discovery-server-0fzo.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

