spring.application.name=SCANNER-SERVICE
server.port=8085

eureka.client.service-url.defaultZone=https://discovery-server-0fzo.onrender.com/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true